Repository cloudspannerecosystem/autoscaler, pull requests merged in 2024-01, with the labels that each got.

#169 Add missing 'ignore' to Dependabot configuration.
  .github/dependabot.yaml
Labels: bug, github_actions

#170 Ensure variables are correctly scoped for try/catch
  src/forwarder/index.js
  src/poller/poller-core/index.js
  src/scaler/scaler-core/index.js
Labels: bug

#172 Add Tscompiler compilation and syntax/type checking of JS files
  jsconfig.json
  package-lock.json
  package.json
  src/forwarder/index.js
  src/forwarder/package-lock.json
  src/forwarder/package.json
  src/index.js
  src/poller/poller-core/index.js
  src/poller/poller-core/package-lock.json
  src/poller/poller-core/package.json
  src/scaler/scaler-core/index.js
  src/scaler/scaler-core/package-lock.json
  src/scaler/scaler-core/package.json
  src/scaler/scaler-core/state.js
  src/scaler/scaler-core/test/index.test.js
  src/scaler/scaler-core/test/scaling-methods/base.test.js
  src/scaler/scaler-core/test/scaling-methods/direct.test.js
  src/scaler/scaler-core/test/scaling-methods/linear.test.js
  src/scaler/scaler-core/test/scaling-methods/stepwise.test.js
  src/scaler/scaler-core/test/test-utils.js
  src/scaler/scaler-core/utils.js
Labels: code health, javascript

#176 Add TS compiler to code health checks workflow
  .github/workflows/codehealth.yaml
  src/package-lock.json
Labels: code health, github_actions

#177 Add unit tests for nodejs v20
  .github/workflows/unit_tests.yaml
Labels: testing, github_actions

#178 Update forwarder in line with poller and scaler
  src/forwarder/index.js
  src/forwarder/package-lock.json
  src/forwarder/package.json
  src/index.js
  terraform/modules/forwarder/main.tf
  terraform/modules/forwarder/variables.tf
Labels: code health, javascript

#184 Require explicit region/zone parameters, remove defaults
  terraform/cloud-functions/distributed/app-project/main.tf
  terraform/cloud-functions/distributed/app-project/variables.tf
  terraform/cloud-functions/distributed/autoscaler-project/main.tf
  terraform/cloud-functions/distributed/autoscaler-project/variables.tf
  terraform/cloud-functions/per-project/main.tf
  terraform/cloud-functions/per-project/test/per_project_e2e_test.go
  terraform/cloud-functions/per-project/variables.tf
  terraform/gke/decoupled/main.tf
  terraform/gke/decoupled/variables.tf
  terraform/gke/unified/main.tf
  terraform/gke/unified/variables.tf
  terraform/modules/autoscaler-base/variables.tf
  terraform/modules/autoscaler-functions/variables.tf
  terraform/modules/firestore/variables.tf
  terraform/modules/forwarder/variables.tf
  terraform/modules/scheduler/main.tf
  terraform/modules/scheduler/variables.tf
  terraform/modules/spanner/variables.tf
Labels: bug

#185 Minor docs updates
  terraform/cloud-functions/distributed/README.md
  terraform/cloud-functions/per-project/README.md
  terraform/gke/README.md
Labels: documentation
