Repository cloudspannerecosystem/autoscaler, pull requests merged in 2024-06, with the labels that each got.

#284 feat: Add metric for scaling duration
  src/autoscaler-common/counters_base.js
  src/poller/README.md
  src/scaler/scaler-core/counters.js
  src/scaler/scaler-core/index.js
  src/scaler/scaler-core/state.js
  src/scaler/scaler-core/test/index.test.js
  src/scaler/scaler-core/test/state.test.js
  src/scaler/scaler-core/test/test-utils.js
  terraform/cloud-functions/distributed/README.md
  terraform/cloud-functions/per-project/README.md
  terraform/gke/README.md
  terraform/modules/spanner/main.tf
Labels: enhancement, javascript

#316 feat: Add markdown link checker
  .github/workflows/codehealth.yaml
  .husky/pre-commit
  package-lock.json
  package.json
Labels: documentation, code health, github_actions

#288 fix: Update packages and replace Bunyan with Pino
  package-lock.json
  package.json
  src/autoscaler-common/logger.js
Labels: javascript
