Repository cloudspannerecosystem/autoscaler, pull requests merged in 2024-10, with the labels that each got.

#396 fix: Version bump for security vuln
  package-lock.json
Labels: dependencies

#397 test: Minor debug QoL improvement for E2E test
  terraform/cloud-functions/per-project/test/per_project_e2e_test.go
Labels: testing

#196 chore: Update from functions to functions2
  README.md
  autoscaler-config.schema.json
  src/autoscaler-common/counters_base.js
  src/functions.js
  src/poller/README.md
  src/scaler/scaler-core/index.js
  terraform/README.md
  terraform/cloud-functions/README.md
  terraform/cloud-functions/centralized/README.md
  terraform/cloud-functions/distributed/README.md
  terraform/cloud-functions/per-project/README.md
  terraform/gke/README.md
  terraform/gke/decoupled/README.md
  terraform/gke/unified/README.md
  terraform/modules/autoscaler-functions/main.tf
  terraform/modules/forwarder/main.tf
Labels: enhancement
